### ISSUE TITLE
Request for XPathExpressionBuilder<Element>

### ISSUE THREAD

**Issue by skiwi2** [hunterhacker/jdom#132]
Could you consider adding a (mutable) XPathExpressionBuilder<Element> to the API?

I find myself defining XPathExpression's like this now:

    private static final Namespace XHTML = Namespace.getNamespace("h", "http://www.w3.org/1999/xhtml");
    
    private static final XPathExpression<Element> XPE_PAGE = FACTORY.compile(
        "/h:html/h:body/h:div[@class='ocr_page']",
        Filters.element(),
        null,
        XHTML
    );

    private static final XPathExpression<Element> XPE_AREA = FACTORY.compile(
        "h:div[@class='ocr_carea']",
        Filters.element(),
        null,
        XHTML
    );
    
    private static final XPathExpression<Element> XPE_PARAGRAPH = FACTORY.compile(
        "h:p[@class='ocr_par']",
        Filters.element(),
        null,
        XHTML
    );
    
    private static final XPathExpression<Element> XPE_LINE = FACTORY.compile(
        "h:span[@class='ocr_line']",
        Filters.element(),
        null,
        XHTML
    );
    
    private static final XPathExpression<Element> XPE_WORD = FACTORY.compile(
        "h:span[@class='ocrx_word']",
        Filters.element(),
        null,
        XHTML
    );

While the following would be miles better in my humble opinion:

```
private static final Namespace XHTML = Namespace.getNamespace("h", "http://www.w3.org/1999/xhtml");

private static final XPathExpressionBuilder<Element> XPE_BUILDER = 
    new XPathExpressionBuilder<Element>()
    .filter(Filters.element())
    .variables(null)
    .namespaces(XHTML);

private static final XPE_PAGE = 
    XPE_BUILDER.expression("/h:html/h:body/h:div[@class='ocr_page']").build();

private static final XPE_AREA =
    XPE_BUILDER.expression("h:div[@class='ocr_carea']").build();

private static final XPE_PARAGRAPH =
    XPE_BUILDER.expression("h:p[@class='ocr_par']").build();

private static final XPE_LINE =
    XPE_BUILDER.expression("h:span[@class='ocr_line']").build();

private static final XPE_WORD =
    XPE_BUILDER.expression("h:span[@class='ocrx_word']").build();
```

This would be more concise, I have not correctly implemented the factory methods in this very simple draft, as I'm not sure how to approach it and it is just an idea.

**Comment by rolfl** [comment]
Reviewing this issue, again, I initially found myself agreeing with it. The current XPathBuilder class takes the expression and finlter as part of the constructor, making it hard to change the expression for each value.

On further reflection, I believe you have just missed another way of doing it, which in a sense is better:

```java
private static final Namespace XHTML = Namespace.getNamespace("h", "http://www.w3.org/1999/xhtml");

private static final XPathFactory XPFACTORY = XPathFactory.instance();

private static final XPathExpression<Element> XPE_PAGE =
    XPFACTORY.compile("/h:html/h:body/h:div[@class='ocr_page']", Filters.element(), null, XHTML);

private static final XPathExpression<Element> XPE_AREA<Element> =
    XPFACTORY.compile("h:div[@class='ocr_carea']", Filters.element(), null, XHTML);

private static final XPathExpression<Element> XPE_PARAGRAPH =
    XPFACTORY.compile("h:p[@class='ocr_par']", Filters.element(), null, XHTML);

private static final XPathExpression<Element> XPE_LINE =
    XPFACTORY.compile("h:span[@class='ocr_line']", Filters.element(), null, XHTML);

private static final XPathExpression<Element> XPE_WORD =
    XPFACTORY.compile("h:span[@class='ocrx_word']", Filters.element(), null, XHTML);
```
