### ISSUE TITLE
Maven artifact jdom-sources includes the source for tests, and samples, not just the core.

### ISSUE THREAD

**Issue by rolfl** [hunterhacker/jdom#150]
The Maven artifact deployed is just the core JDOM library, but the accompanying source jar contains the unit tests and sample/contrib code (which is not in the compiled/deployed jar).

To prevent issues where people expect to see all the classes in the source jar compiled in to the compiled jar, the unused sources should be removed

**Comment by trejkaz** [comment]
The classes for the tests are also in the jdom2 jar too... this seems like a slip-up.

```
.../jdom2-2.0.6.jar
  org.jdom2.test.cases
    TestAttribute
      test_TCM__boolean_equals_Object()
        assertFalse("attribute equal to null", attribute.equals(null));
      test_TCM__int_hashCode()
        assertFalse("Different Attributes with same value have same hashcode", x == i);
        assertFalse("Different Attributes have same hashcode", y == x);
        import static org.junit.Assert.assertFalse;
```
