### ISSUE TITLE
Method SAXBuilder.build(java.io.Reader characterStream) closes stream

### ISSUE THREAD

**Issue by Raven-Pro** [hunterhacker/jdom#152]
The stream is closed by method build(), and that action, only corresponds to the developer who created the instance of the class Reader.

**Comment by rolfl** [comment]
While this may be inconvenient, it is also by-design. This comes from the definition of an InputSource that is used to parse XML documents: http://docs.oracle.com/javase/8/docs/api/org/xml/sax/InputSource.html Note that it says: "...standard processing of both byte and character streams is to close them on as part of end-of-parse cleanup, so applications should not attempt to re-use such streams after they have been handed to a parser.".

The stream is not closed by JDOM, but by the underlying (xerces, or Java) infrastructure.

Note that you can wrap the reader in a FilterReader that has the close() Method overridden to do nothing.
