### ISSUE TITLE
Jaxen Dependency Support Issue

### ISSUE THREAD

**Issue by codeblooded** [hunterhacker/jdom#157]
I stumbled across a dependency issue. I was trying to throw together a prototype without using maven or any dependency manager. It was 1 file. I hit an issue when I tried to download jaxen binaries.

_jdom_ relies on Jaxen. I do not know if this project is still maintained. It has not been updated in quite some time, and I cannot download the binaries b/c codehaus has shutdown. I found the src here: https://github.com/codehaus/jaxen and I can access through maven. Does anyone know if this project is still active? Will the jdom project take over the src code if it isn't?

**Comment by codeblooded** [comment]
Just want to make sure jdom will continue to improve and an unmaintained dependency won't stop that. Love the library! Thanks!

**Comment by rolfl** [comment]
Jaxen is still maintained by Elliotte. The jaxen.org site was "locked out", I believe. The jaxen-dev mailing list archive now also not-up-to-date, it seems. Elliotte anticipated that. This is the communication I got at the time:

> This mailing list will likely be dead soon. You can contact me privately at elharo@..... or send github pull requests. I will try to find a new mailing list host, but it's a low prioritiy at the moment.
> 
> No one has stepped forward to help with the Jira migration, and I haven't been able to get any answers from Atlassian except form email, so the bug database is likely lost. We'll use the github bug tracker for now. If there are any open issues, you really care about start copying and pasting.
> 
> If you notice any issues on the new web site <http://www.cafeconleche.org/jaxen/> let me know or, better yet, fix the relevant file in the xdcos folder and send a pull request.
> 
> Also, the github wiki should be edited soon. If anyone wants to help out with that, please do. 

Note that the github source is at: https://github.com/jaxen-xpath/jaxen

Also, note that both JDOM and Jaxen are somewhat mature, so changes happen infrequently (not much changes in the XPath/XML world and both products are essentially "feature complete").
