### ISSUE TITLE
LocatedText column indices are unregular / not as expected

### ISSUE THREAD

**Issue by fhennig** [hunterhacker/jdom#159]
Hi, i wanted to use the LocatedText objects to keep track of where text was in my original document. However, the indices provided are following some weird rules, I made an example to demonstrate.

This is my sample XML document:
```
<doc>
  <s>
    This is <i>my</i> Text.
  </s>
  More Text.

</doc>
```

And this is my code I use for parsing:
```
SAXBuilder jdomBuilder = new SAXBuilder();
jdomBuilder.setJDOMFactory(new LocatedJDOMFactory());
org.jdom2.Document doc = jdomBuilder.build(new File("filename"));
XMLOutputter printer = new XMLOutputter();
	LocatedElement elem = (LocatedElement)doc.getRootElement();
	for (Content x : elem.getDescendants()) {
	Content.CType type = x.getCType();
	if (type == Content.CType.Text) {
		LocatedText txt = (LocatedText)x;
		System.out.println(String.format("(%d, %d): '%s'", txt.getLine(), txt.getColumn(), txt.getText()));
	}
}
```

This is the output I get:
```
(2, 4): '
  '
(3, 14): '
    This is '
(3, 20): 'my'
(4, 3): ' Text.
  '
(7, 1): '
  More Text.

'
```

First thing I noticed everything seems to be at least one off, so I assumed the column index is 1-based. Under this assumption, the 'This is' ends in the `<i>` tag, right on the `i`. Same for the 'my', it also ends on the `i` in `</i>`. I would have expected both of them to end right at the `<` of the next tag. 

Now for the 'More Text.' at the end, it is again different. This text ends at (7, 1), which is right on the `<` of `</doc>`. I think this makes the most sense, but not if one takes into account the other two phenomena described above. Also If one removes the newlines, the text ends again on the `d` from `</doc>`. 

I want to know if this behavior is a bug and can be fixed, or if it is intended and if so, how I can reliably work with these values.

**Comment by rolfl** [comment]
The basic answer to your question is that you can't reliably work with these values. The behaviour of these values is inherited from the SAX data sent to the JDOM handlers when processing the content. The data is defined by the `Locator` instance. Here's the JavaDoc for that: http://docs.oracle.com/javase/8/docs/api/org/xml/sax/Locator.html#getColumnNumber--

This is not something JDOM can control.

Note that the documentation contains:

> Return the column number where the current document event ends. This is one-based number of Java char values since the last line end.
> Warning: The return value from the method is intended only as an approximation for the sake of diagnostics; it is not intended to provide sufficient information to edit the character content of the original XML document. For example, when lines contain combining character sequences, wide characters, surrogate pairs, or bi-directional text, the value may not correspond to the column in a text editor's display.
> 
> The return value is an approximation of the column number in the document entity or external parsed entity where the markup triggering the event appears.
> 
> If possible, the SAX driver should provide the line position of the first character after the text associated with the document event. The first column in each line is column 1.

At best, the value is an approximation for diagnostics.

**Comment by fhennig** [comment]
Ok thanks!
