### ISSUE TITLE
JDOM website down

### ISSUE THREAD

**Issue by sillyfly** [hunterhacker/jdom#160]
Not sure if this is the correct place, but can't find any better place to post - 

For the last two days (at least), http://jdom.org returns "Forbidden" for any request, effectively making the site unusable.

**Comment by rolfl** [comment]
Yes, this is a good place to report it. Thanks. Investigating.

**Comment by rolfl** [comment]
Site is restored, still waiting to see if there is a root-cause of the failure, but closing for the moment.

**Comment by hunterhacker** [comment]
Yesterday I filed a ticket with the ISP that hosts the box.  Earlier today they fixed it and said, "It looks as though Apache 1.3 was started instead of Apache 2".

No explanation given why any servers were restarting at all.  :)
