### ISSUE TITLE
Support wrapping long lines at configured width

### ISSUE THREAD

**Issue by mattnelson** [hunterhacker/jdom#170]
Took a quick look at the issues/source and didn't see this implemented or previously requested.

Would it be possible to support configuration of a maximum line length to wrap lines?

Related to Ekryd/sortpom#38

**Comment by Ekryd** [comment]
Please note that SortPom uses an old version of Jdom.  Any new features of Jdom will not be included in the SortPom plugin. This is due to architecural and programming decisions many years ago.

**Comment by rolfl** [comment]
It's not the role of JDOM to impose "style" constraints on XML content. This should be done external-to-JDOM
