### ISSUE TITLE
Include an automatic module name in the manifest

### ISSUE THREAD

**Issue by kashike** [hunterhacker/jdom#172]
http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

**Comment by hunterhacker** [comment]
Want to submit a pull request?

**Comment by kashike** [comment]
I was going to, but I haven't worked with ant enough to figure out how to add additional manfiest entries for the contrib JAR.

**Comment by VISTALL** [comment]
Maybe you will interest, see this issue https://github.com/hunterhacker/jdom/issues/174
