### ISSUE TITLE
JAVA 11 compatibility for library jdom2

### ISSUE THREAD

**Issue by bhalgatneha** [hunterhacker/jdom#180]
Hi,
We are reaching out to you to check Java 11 compatibility of the library jdom2.
Could you help us by answering the following questions:

Library Name: jdom2
Latest version: <latest 2="" eg:="" version.="2.0.6">
Latest version Is the library compatible with Java 11 Compatible? (Y/N)
Is the library supported with Java 11? (Y/N)
(If “N” in compatibility or support) What is the versions that would be compatible and Supported?
Date of support availability?
I appreciate your response as early as possible.

Thanks,
Neha Bhalgat
PTC India Pvt. Ltd.

**Comment by hunterhacker** [comment]
JDOM is open source software. What level of support is PTC India expecting for the grand total of $0 per year that they’re paying?

There’s tests included with the distribution. They’re intended for you to use them to test compatibility with different environments. If you hit a snag, a pull request with a fix would be lovely.
