### ISSUE TITLE
Update to jaxen 1.2.0

### ISSUE THREAD

**Issue by trancexpress** [hunterhacker/jdom#186]
My team is in the process of updating an Eclipse-based product to compile with Java 11. Among other problems, we run into split package problems with `jdom 2.0.4`:

`[javac] The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml`

This seems to be due to version of `jaxen` used in the `jdom` bundle; the `jaxen` version has the class `org.w3c.dom.UserDataHandler`, causing the compile error. We would like to avoid use of `--limit-modules` and compile cleanly; we checked the latest available `jdom 2.0.6` but it contains `jaxen 1.1.6` (up from `jaxen 1.1.4` in our case). Unfortunately this `jaxen` version still contains a `org.w3c.dom` package.

`jaxen 1.2.0` on the other hand does not. So it would be great if a `jdom` bundle is available with `jaxen 1.2.0`, to support applications that compile against JDK 9+.

**Comment by hunterhacker** [comment]
Simeon, do you want to take the lead on a release? Rolf had been doing it but he's gone silent (not sure why, hoping for the best).

**Comment by trancexpress** [comment]
I've consulted my team, we'll try to separate the `jaxen` dependency in the current `jdom` release we use. So that we don't compile against `jaxen` (which we don't need).

Our hands are unfortunately full already, we cannot devote time to preparing `jdom` release.

**Comment by rolfl** [comment]
And, I have resurfaced. Apologies, I was inadvertently sending all my JDOM correspondence in to an unmonitored mail folder.... This issue will take some finangling to get the builds through. There's a fair backlog I need to address, this will be part of it.

**Comment by trancexpress** [comment]
Thanks!
