### ISSUE TITLE
Errant characters at start of XML file (but absent in console dump)

### ISSUE THREAD

**Issue by pbierre** [hunterhacker/jdom#193]
This bug has been replicated on a Mac and a Win10 Dell.

Environment (Mac and Win10):  
JDOM-2 2.0.6 (jars only) installed on 07/04/2021 at 14:39 PDT.
Java 1.8.0_291 (the final published Java 8 JDK)

Mac: OS 10.13.6 High Sierra on 2011 Intel Core i3
Win: Windows10 64b Home v 21H1 OS build 19043.1110 on Dell Inspiron Intel Core i5-3330S

I'm generating an XML-format file to save User data from my app, for persistent storage.  I'm using the simplest possible approach, e.g.,

Document outputDoc = new Document();
outputDoc.setRootElement(new Element("GraphicalAlgorithm_" + challengeID, DFG2D_NAMESPACE));

Element entireTableXmlElement = generateReferenceObjectTableXMLElement();
outputDoc.getRootElement().addContent(entireTableXmlElement);

XMLOutputter xmlOutputter = new XMLOutputter(Format.getPrettyFormat());

//TEST ONLY: writes to console
		xmlOutputter.output(outputDoc, System.out);
	
xmlOutputter.output(outputDoc, fileStream);

The SAXBuilder chokes on the XML file, and the reason can be seen here -- errant characters at the start of the generated file.  

Mac result seen in TextEdit:
![IMG_3549](https://user-images.githubusercontent.com/2850557/125997996-0f88b5cd-95ae-4e85-9d9b-f00b00ba6ae3.JPG)

Win10 result seen in Notepad:
![IMG_3547](https://user-images.githubusercontent.com/2850557/125998069-b388aae0-5cea-4b4a-82ae-72fd6987672c.JPG)

Perplexing is the fact that when the XMLOutputter is directed to render the same doc --> console, the XML dump looks normal:
![IMG_3548](https://user-images.githubusercontent.com/2850557/125998233-ab7faceb-93a5-4547-81f8-e6a4fffbc7f1.JPG)

I'm attaching a small XML file generated on the Mac for your analysis:
[exampleExtraChars.txt](https://github.com/hunterhacker/jdom/files/6832925/exampleExtraChars.txt)

I'm using Eclipse for Java SE as my IDE.  As far as testing goes, I've tried generating the XML without the Prolog, and you still get the errant characters.   It's 100% repeatable on Mac and Win10 runs of my app.

If I dump to a character byte stream, I can likely trim the first 4 bytes, and send it off to an OutputStream.   But, this is a fairly unsubtle bug to be discovering as a developer utilizing a mature open-source JDOM package.  I'm stumped.

After I manually strip out these junk bytes with a text editor, the XML file parses correctly using SAXBuilder.

If you can't replicate the bug, feel free to suggest some test scenarios I could run to flush out the root cause.

**Comment by hunterhacker** [comment]
That gibberish in raw bytes looks to be 0xAC 0xED 0x00 0x05 which is the 4-byte magic byte prefix for the Java serialization format. It’s like your fileStream is an ObjectOutputStream?

**Comment by pbierre** [comment]
Thanks, I'll look into that.  I prototyped my app using Java Serialization as a file storage crutch until I could replace that with XML persistent file storage.   I have .ser output file generation switched off using a run-time flag, but the Java compiler wouldn't know that.   The classes I'm decoding into XML are still declared "implements Serializable".   Will look into this, and report back.

**Comment by pbierre** [comment]
OK, I got to the bottom of this.   When I went to convert from Serialization storage to XML, I copied and pasted code that I never understood well, and had just a year ago hoarked from some example of how to output a Serialized file:

	//************* saveAlgorithmToXMLFile ****************
	public void saveAlgorithmToXMLFile(File file, GraphicalAlgorithm graphicalAlgorithm) {
			XMLPersistantGraphicalAlgorithm XML_Algo = null; 
    		FileOutputStream fos = null;
    		ObjectOutputStream out = null;
    		
    		try {
    			fos = new FileOutputStream(file);
    			out = new ObjectOutputStream(fos);

    	        XML_Algo = new XMLPersistantGraphicalAlgorithm(graphicalAlgorithm);		
    	        XML_Algo.writeFileUsingJDOM(fos);

    			fos.close();
    			
    		}
    		catch(IOException ex)
    		{
    			System.out.println("failed on IO during XML algo file write cycle");
    			ex.printStackTrace();
    		}
    		
    		
    		
			XML_Algo.repairXMLOutputFile(file); // TEMPORARY FIX TO ERRANT BYTES BUG

	}


Even though I'm passing the "fos" (FileOutputStream) variable to the XML file writer, not the "out" (ObjectOutputStream) variable, the fact that I had attached an ObjectOutputStream "out" to "fos" before calling my writeXML, this seems to be telling "fos" to expect a Serialization file writer to be invoked.  Rather than waiting to see if a serializing "writeObject" is even called, "fos" commits to prefacing the output file with the 4-byte Serialization "magic ID".

All I had to do to correct the problem bytes was to comment out the line that calls the ObjectOutputStream constructor, and just eliminate that variable:
			XMLPersistantGraphicalAlgorithm XML_Algo = null; 
    		FileOutputStream fos = null;
    		//ObjectOutputStream out = null;
    		
    		try {
    			fos = new FileOutputStream(file);
    			//out = new ObjectOutputStream(fos);

    	        XML_Algo = new XMLPersistantGraphicalAlgorithm(graphicalAlgorithm);		
    	        XML_Algo.writeFileUsingJDOM(fos);

The good news is that it's not a bug in JDOM-2.    It's rather a minefield a math-scientific programmer like me, someone who in a team environment always got another programmer to do file IO, stepped into converting from .ser to .xml.   I'll post a topic on StackOverflow to help the next similar victim of "copy and paste" file I/O development.  

Thanks, Jason!

**Comment by pbierre** [comment]
Jason, go ahead and close this one.

**Comment by ar** [comment]
Oh... talk me about side effects!

**Comment by pbierre** [comment]
"copy and paste" -- the greatest programming tool ever invented!

**Comment by hunterhacker** [comment]
Glad you solved it
