### ISSUE TITLE
Keep the original formatting of source file for all lines

### ISSUE THREAD

**Issue by ManjunathMS35** [hunterhacker/jdom#198]
Hello,

I use jdom for parsing Maven pom.xml, I have a use case where I have to preserve the formatting for the modified pom's.

The jdom does great in preserving all source file formatting, except the first line which is the namespace line and the last line.

For example,

`<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">`

If the above namespace is divided into two lines or more in source file, jdom will format it to a single line after modification and in the last line of pom.xml it removes the newline character.

I use the below format settings in jdom,

`  Format format = Format.getRawFormat();
    format.setLineSeparator("");
    format.setTextMode(Format.TextMode.PRESERVE);`
    
    Is it possible to not modify these two lines from adding/changing any format settings or is it a default behaviour?

**Comment by hunterhacker** [comment]
JDOM stores and manipulates the semantic model of the source XML, not the serialized textual model. Loading a document and then serializing it may change the output in numerous ways from the text model of the source document. Whitespace outside the root element might not be preserved. Attributes may be reordered. Character encoding sequences might change. None of this changes the meaning of the XML, but might change the byte sequence. People often ask for the serialized textual model to be preserved exactly (so they can hash it or whatever to look for differences), but the XML parsers don't preserve it (and aren't required to) so it's gone before JDOM even gets told what's in the file. There's nothing we can do about it. And this is how XML was designed. A given XML model is allowed to have a nearly infinite number of semantically equivalent textual representations.
