### ISSUE TITLE
Possible Null Pointer Dereference in SAXHandler.java

### ISSUE THREAD

**Issue by ZuhairORZaki** [hunterhacker/jdom#220]
# Reporting a bug found by iCR

In file: [SAXHandler.java](https://github.com/hunterhacker/jdom/blob/JDOM-2.0.6.1/core/src/java/org/jdom2/input/sax/SAXHandler.java#L918), there is a potential case of null pointer dereference. In method `endDTD` inside class `SAXHandler`, there is a call to `currentDocument.getDocType`. Here `currentDocument` is an object of class `Document`.

```java
	@Override
	public void endDTD() {

		currentDocument.getDocType().setInternalSubset(
				internalSubset.toString());
		inDTD = false;
		inInternalSubset = false;
	}
```

Then `setInternalSubset` method is invoked on the supposedly returned `DocType` object. But `getDocType` method of class `Document` can return null under a certain condition, namely `index < 0`.

```java
	public DocType getDocType() {
		int index = content.indexOfDocType();
		if (index < 0) {
			return null;
		}
		return (DocType) content.get(index);
	}
```

If that happens it will cause a `NullPointerException`.

It is not immediately clear whether `index` would always be non-negative for `currentDocument` in  `endDTD` method. If that is indeed the case, you may choose to ignore this issue.

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by hunterhacker** [comment]
Doesn't seem like you'd ever get endDTD() called without a DocType present.
