### ISSUE TITLE
Website is unavailable

### ISSUE THREAD

**Issue by a474c** [hunterhacker/jdom#222]
Hello,

The JDOM website has been unavailable since last August, according to the Wayback Machine.
All I receive is this message:

> Forbidden
> You don't have permission to access / on this server.

I wanted to use the latest binary version, which was not included on the GitHub release page, but fortunately, I managed to find it in the website’s repository.
I’m not sure whether this is intentional, but, if so, the website should probably be removed from the project README.

Thanks.

**Comment by hunterhacker** [comment]
Eek! I asked the support folks to look into this.

**Comment by hunterhacker** [comment]
Support kicked the box. Happy again.

**Comment by a474c** [comment]
Thank you very much for fixing this. It’s really appreciated. Many websites and schools still use JDOM in their courses, and the website that offers the binary version makes everything much easier.
